#!/bin/sh

sudo yum install -y docker
sudo service docker start
sudo docker run \
  -u root \
  --rm \
  -d \
  -p 8080:8080 \
  -p 50000:50000 \
  -v jenkins-data:/var/jenkins_home \
  -v /var/run/docker.sock:/var/run/docker.sock \
  jenkinsci/blueocean
#sudo docker logs $CONTAINER_ID #to get jenkins password here
#http://54.193.114.103:8080/blue/pipelines
